extends RefCounted
class_name EventContracts

const ITEM_ACQUIRED: StringName = &"ITEM_ACQUIRED"
const ITEM_USED: StringName = &"ITEM_USED"
const ITEM_EQUIPPED: StringName = &"ITEM_EQUIPPED"
const ITEM_DROPPED: StringName = &"ITEM_DROPPED"
const ITEM_CRAFTED: StringName = &"ITEM_CRAFTED"

const TECHNIQUE_LEARNED: StringName = &"TECHNIQUE_LEARNED"
const TECHNIQUE_MEDITATED: StringName = &"TECHNIQUE_MEDITATED"
const TECHNIQUE_EQUIPPED: StringName = &"TECHNIQUE_EQUIPPED"
const TECHNIQUE_SECT_RESTRICTED: StringName = &"TECHNIQUE_SECT_RESTRICTED"

const COMBAT_STARTED: StringName = &"COMBAT_STARTED"
const COMBAT_TURN_RESOLVED: StringName = &"COMBAT_TURN_RESOLVED"
const COMBAT_ENDED: StringName = &"COMBAT_ENDED"
const COMBAT_FLED: StringName = &"COMBAT_FLED"

const TERRITORY_CHANGED: StringName = &"TERRITORY_CHANGED"
const REGION_RESOURCE_PRODUCED: StringName = &"REGION_RESOURCE_PRODUCED"
const REGION_RESOURCE_DEPLETED: StringName = &"REGION_RESOURCE_DEPLETED"
const FACTION_INFLUENCE_CHANGED: StringName = &"FACTION_INFLUENCE_CHANGED"

const TRADE_COMPLETED: StringName = &"TRADE_COMPLETED"
const CRAFTING_SUCCESS: StringName = &"CRAFTING_SUCCESS"
const CRAFTING_FAILURE: StringName = &"CRAFTING_FAILURE"

const ITEM_EVENTS: Array[StringName] = [
	ITEM_ACQUIRED,
	ITEM_USED,
	ITEM_EQUIPPED,
	ITEM_DROPPED,
	ITEM_CRAFTED,
]

const TECHNIQUE_EVENTS: Array[StringName] = [
	TECHNIQUE_LEARNED,
	TECHNIQUE_MEDITATED,
	TECHNIQUE_EQUIPPED,
	TECHNIQUE_SECT_RESTRICTED,
]

const COMBAT_EVENTS: Array[StringName] = [
	COMBAT_STARTED,
	COMBAT_TURN_RESOLVED,
	COMBAT_ENDED,
	COMBAT_FLED,
]

const WORLD_EVENTS: Array[StringName] = [
	TERRITORY_CHANGED,
	REGION_RESOURCE_PRODUCED,
	REGION_RESOURCE_DEPLETED,
	FACTION_INFLUENCE_CHANGED,
]

const ECONOMY_EVENTS: Array[StringName] = [
	TRADE_COMPLETED,
	CRAFTING_SUCCESS,
	CRAFTING_FAILURE,
]

const ALL_EVENTS: Array[StringName] = [
	ITEM_ACQUIRED,
	ITEM_USED,
	ITEM_EQUIPPED,
	ITEM_DROPPED,
	ITEM_CRAFTED,
	TECHNIQUE_LEARNED,
	TECHNIQUE_MEDITATED,
	TECHNIQUE_EQUIPPED,
	TECHNIQUE_SECT_RESTRICTED,
	COMBAT_STARTED,
	COMBAT_TURN_RESOLVED,
	COMBAT_ENDED,
	COMBAT_FLED,
	TERRITORY_CHANGED,
	REGION_RESOURCE_PRODUCED,
	REGION_RESOURCE_DEPLETED,
	FACTION_INFLUENCE_CHANGED,
	TRADE_COMPLETED,
	CRAFTING_SUCCESS,
	CRAFTING_FAILURE,
]
