extends RefCounted
class_name TickOrder

const PHASE_PRODUCTION: StringName = &"PHASE_PRODUCTION"
const PHASE_NPC_DECISION: StringName = &"PHASE_NPC_DECISION"
const PHASE_NPC_ACTION: StringName = &"PHASE_NPC_ACTION"
const PHASE_COMBAT: StringName = &"PHASE_COMBAT"
const PHASE_TERRITORY: StringName = &"PHASE_TERRITORY"
const PHASE_CLEANUP: StringName = &"PHASE_CLEANUP"

const PHASE_ORDER: Array[StringName] = [
	PHASE_PRODUCTION,
	PHASE_NPC_DECISION,
	PHASE_NPC_ACTION,
	PHASE_COMBAT,
	PHASE_TERRITORY,
	PHASE_CLEANUP,
]
